<?php
echo '<AMO FAZER EXERCICIO NO URI>' . PHP_EOL;
echo '<    AMO FAZER EXERCICIO NO URI>' . PHP_EOL;
echo '<AMO FAZER EXERCICIO >' . PHP_EOL;
echo '<AMO FAZER EXERCICIO NO URI>' . PHP_EOL;
echo '<AMO FAZER EXERCICIO NO URI    >' . PHP_EOL;
echo '<AMO FAZER EXERCICIO NO URI>' . PHP_EOL;
echo '<          AMO FAZER EXERCICIO >' . PHP_EOL;
echo '<AMO FAZER EXERCICIO           >' . PHP_EOL;
?>