write(paste('<AMO FAZER EXERCICIO NO URI>'), '')
write(paste('<    AMO FAZER EXERCICIO NO URI>'), '')
write(paste('<AMO FAZER EXERCICIO >'), '')
write(paste('<AMO FAZER EXERCICIO NO URI>'), '')
write(paste('<AMO FAZER EXERCICIO NO URI    >'), '')
write(paste('<AMO FAZER EXERCICIO NO URI>'), '')
write(paste('<          AMO FAZER EXERCICIO >'), '')
write(paste('<AMO FAZER EXERCICIO           >'), '')