IO.puts "---------------------------------------"
IO.puts "|        Roberto                      |"
IO.puts "|                                     |"
IO.puts "|        5786                         |"
IO.puts "|                                     |"
IO.puts "|        UNIFEI                       |"
IO.puts "---------------------------------------"