write(paste('---------------------------------------'), '')
write(paste('|  decimal  |  octal  |  Hexadecimal  |'), '')
write(paste('---------------------------------------'), '')
write(paste('|      0    |    0    |       0       |'), '')
write(paste('|      1    |    1    |       1       |'), '')
write(paste('|      2    |    2    |       2       |'), '')
write(paste('|      3    |    3    |       3       |'), '')
write(paste('|      4    |    4    |       4       |'), '')
write(paste('|      5    |    5    |       5       |'), '')
write(paste('|      6    |    6    |       6       |'), '')
write(paste('|      7    |    7    |       7       |'), '')
write(paste('|      8    |   10    |       8       |'), '')
write(paste('|      9    |   11    |       9       |'), '')
write(paste('|     10    |   12    |       A       |'), '')
write(paste('|     11    |   13    |       B       |'), '')
write(paste('|     12    |   14    |       C       |'), '')
write(paste('|     13    |   15    |       D       |'), '')
write(paste('|     14    |   16    |       E       |'), '')
write(paste('|     15    |   17    |       F       |'), '')
write(paste('---------------------------------------'), '')