IO.puts "---------------------------------------"
IO.puts "|  decimal  |  octal  |  Hexadecimal  |"
IO.puts "---------------------------------------"
IO.puts "|      0    |    0    |       0       |"
IO.puts "|      1    |    1    |       1       |"
IO.puts "|      2    |    2    |       2       |"
IO.puts "|      3    |    3    |       3       |"
IO.puts "|      4    |    4    |       4       |"
IO.puts "|      5    |    5    |       5       |"
IO.puts "|      6    |    6    |       6       |"
IO.puts "|      7    |    7    |       7       |"
IO.puts "|      8    |   10    |       8       |"
IO.puts "|      9    |   11    |       9       |"
IO.puts "|     10    |   12    |       A       |"
IO.puts "|     11    |   13    |       B       |"
IO.puts "|     12    |   14    |       C       |"
IO.puts "|     13    |   15    |       D       |"
IO.puts "|     14    |   16    |       E       |"
IO.puts "|     15    |   17    |       F       |"
IO.puts "---------------------------------------"